name: Publish

on:
  workflow_run:
    workflows: ['Test']
    branches: [master]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow
    - uses: actions/setup-python@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - run: |
        uv venv
        uv sync --group=dev

    - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: uv run ./scripts/publish.sh
